#!/usr/bin/env bun
/**
 * Generate embedded assets manifest for Bun compile
 *
 * Scans packages/web/dist/ and generates a TypeScript file with
 * Bun file imports that get embedded in the compiled binary.
 */

import { readdirSync, statSync, writeFileSync } from 'fs'
import { join, relative, extname } from 'path'

const WEB_DIST = join(import.meta.dir, '../../web/dist')
const OUTPUT_FILE = join(import.meta.dir, '../src/web/embeddedAssets.generated.ts')

// MIME type mapping
const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.webmanifest': 'application/manifest+json',
  '.txt': 'text/plain; charset=utf-8',
}

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase()
  return MIME_TYPES[ext] || 'application/octet-stream'
}

function walkDir(dir: string, baseDir: string = dir): string[] {
  const files: string[] = []

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)

    if (stat.isDirectory()) {
      files.push(...walkDir(fullPath, baseDir))
    } else {
      files.push(fullPath)
    }
  }

  return files
}

function generateAssetFile(): void {
  console.log(`Scanning: ${WEB_DIST}`)

  const files = walkDir(WEB_DIST)
  console.log(`Found ${files.length} files`)

  const imports: string[] = []
  const assets: string[] = []

  files.forEach((filePath, index) => {
    const relativePath = relative(WEB_DIST, filePath)
    const urlPath = '/' + relativePath.replace(/\\/g, '/')
    const importPath = `../../../web/dist/${relativePath.replace(/\\/g, '/')}`
    const mimeType = getMimeType(filePath)
    const ext = extname(filePath).toLowerCase()

    imports.push(`import asset${index} from '${importPath}' with { type: 'file' };`)

    // For JSON files, TypeScript infers the JSON object type instead of string
    // Bun's { type: 'file' } returns a file path string at runtime, so we cast it
    const fileValue = ext === '.json' ? `asset${index} as unknown as string` : `asset${index}`
    assets.push(`  { path: '${urlPath}', file: ${fileValue}, mimeType: '${mimeType}' },`)

    console.log(`  ${urlPath} → ${mimeType}`)
  })

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun scripts/generate-embedded-assets.ts
 */

${imports.join('\n')}

export interface EmbeddedAsset {
  path: string;
  file: string;
  mimeType: string;
}

export const embeddedAssets: EmbeddedAsset[] = [
${assets.join('\n')}
];
`

  writeFileSync(OUTPUT_FILE, output)
  console.log(`\nGenerated: ${OUTPUT_FILE}`)
}

generateAssetFile()
